server:
  port: 8010
spring:
  application:
    name: microservice-consumer-movie-ribbon
eureka:
  client:
    serviceUrl:
      defaultZone: http://luva.peer1:8761/eureka/,http://luva.peer2:8762/eureka/
  instance:
    preferIpAddress: true