server:
  port: 8000
spring:
  application:
    name: microservice-provider-user
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    data:
    - classpath:data.sql
    platform: h2
    schema:
    - classpath:schema.sql
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    hulva.luva.learn.springcloudmicroservicestudy.provideruser.persistence: ERROR
eureka:
  client:
    service-url:
      defaultZone: http://luva.peer1:8761/eureka/,http://luva.peer2:8762/eureka/
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true